### ISSUE TITLE
Support common Quarkus errors

### ISSUE THREAD

**Issue by SchulteMarkus** [cloudstark/quarkus-problem-extension#3]
In REST, there are common errors such as 404/NOT_FOUND, 401/UNAUTHORIZED etc.
Quarkus itself is handling these errors. This can be seem in the [package io.quarkus.resteasy.runtime]( https://github.com/quarkusio/quarkus/tree/master/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime), where some javax.ws.rs.ext.ExceptionMapper are implemented ([ForbiddenExceptionMapper](https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/ForbiddenExceptionMapper.java#L16) for example).

When using this quarkus-problem-extension, there is still not a "problem" returned in case one of these common errors occurs:

```bash
$ curl -v http://localhost:8080/notpresent
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /notpresent HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Length: 0
< Content-Type: application/json
```

**Feature request**: In case of a common error, return a "problem", too.

**Comment by CrystalMethod** [comment]
fixed with 268cb33057246601fcf4ec529f51c85e0d387a26
